/** Canonical Bible metadata — all 66 books (OT + NT). */
export const ALL_BOOK_SLUGS = [
  "genesis",
  "exodus",
  "leviticus",
  "numbers",
  "deuteronomy",
  "joshua",
  "judges",
  "ruth",
  "1-samuel",
  "2-samuel",
  "1-kings",
  "2-kings",
  "1-chronicles",
  "2-chronicles",
  "ezra",
  "nehemiah",
  "esther",
  "job",
  "psalms",
  "proverbs",
  "ecclesiastes",
  "song-of-solomon",
  "isaiah",
  "jeremiah",
  "lamentations",
  "ezekiel",
  "daniel",
  "hosea",
  "joel",
  "amos",
  "obadiah",
  "jonah",
  "micah",
  "nahum",
  "habakkuk",
  "zephaniah",
  "haggai",
  "zechariah",
  "malachi",
  "matthew",
  "mark",
  "luke",
  "john",
  "acts",
  "romans",
  "1-corinthians",
  "2-corinthians",
  "galatians",
  "ephesians",
  "philippians",
  "colossians",
  "1-thessalonians",
  "2-thessalonians",
  "1-timothy",
  "2-timothy",
  "titus",
  "philemon",
  "hebrews",
  "james",
  "1-peter",
  "2-peter",
  "1-john",
  "2-john",
  "3-john",
  "jude",
  "revelation",
];

/** Mobile demo slices — keep in sync with create-mobile-seed.mjs */
export const MOBILE_SLICES = [
  { slug: "genesis", chapter: 1 },
  { slug: "psalms", chapter: 23 },
  { slug: "john", chapter: 1 },
  { slug: "romans", chapter: 8, verses: [26, 31] },
];

/** Thayer/KJV JSON abbrev → app slug */
export const KJV_ABBREV_TO_SLUG = {
  gn: "genesis",
  ex: "exodus",
  lv: "leviticus",
  nm: "numbers",
  dt: "deuteronomy",
  js: "joshua",
  jud: "judges",
  rt: "ruth",
  "1sm": "1-samuel",
  "2sm": "2-samuel",
  "1kgs": "1-kings",
  "2kgs": "2-kings",
  "1ch": "1-chronicles",
  "2ch": "2-chronicles",
  ezr: "ezra",
  ne: "nehemiah",
  et: "esther",
  job: "job",
  ps: "psalms",
  prv: "proverbs",
  ec: "ecclesiastes",
  so: "song-of-solomon",
  is: "isaiah",
  jr: "jeremiah",
  lm: "lamentations",
  ez: "ezekiel",
  dn: "daniel",
  ho: "hosea",
  jl: "joel",
  am: "amos",
  ob: "obadiah",
  jn: "jonah",
  mi: "micah",
  na: "nahum",
  hk: "habakkuk",
  zp: "zephaniah",
  hg: "haggai",
  zc: "zechariah",
  ml: "malachi",
  mt: "matthew",
  mk: "mark",
  lk: "luke",
  jo: "john",
  act: "acts",
  rm: "romans",
  "1co": "1-corinthians",
  "2co": "2-corinthians",
  gl: "galatians",
  eph: "ephesians",
  ph: "philippians",
  cl: "colossians",
  "1ts": "1-thessalonians",
  "2ts": "2-thessalonians",
  "1tm": "1-timothy",
  "2tm": "2-timothy",
  tt: "titus",
  phm: "philemon",
  hb: "hebrews",
  jm: "james",
  "1pe": "1-peter",
  "2pe": "2-peter",
  "1jo": "1-john",
  "2jo": "2-john",
  "3jo": "3-john",
  jd: "jude",
  re: "revelation",
};

/** midvash/bible-data book file stems (versions/pl/bg/books/*.json) */
export const MIDVASH_BOOK_FILES = {
  genesis: "Gen",
  exodus: "Exod",
  leviticus: "Lev",
  numbers: "Num",
  deuteronomy: "Deut",
  joshua: "Josh",
  judges: "Judg",
  ruth: "Ruth",
  "1-samuel": "1Sam",
  "2-samuel": "2Sam",
  "1-kings": "1Kgs",
  "2-kings": "2Kgs",
  "1-chronicles": "1Chr",
  "2-chronicles": "2Chr",
  ezra: "Ezra",
  nehemiah: "Neh",
  esther: "Esth",
  job: "Job",
  psalms: "Ps",
  proverbs: "Prov",
  ecclesiastes: "Eccl",
  "song-of-solomon": "Song",
  isaiah: "Isa",
  jeremiah: "Jer",
  lamentations: "Lam",
  ezekiel: "Ezek",
  daniel: "Dan",
  hosea: "Hos",
  joel: "Joel",
  amos: "Amos",
  obadiah: "Obad",
  jonah: "Jonah",
  micah: "Mic",
  nahum: "Nah",
  habakkuk: "Hab",
  zephaniah: "Zeph",
  haggai: "Hag",
  zechariah: "Zech",
  malachi: "Mal",
  matthew: "Matt",
  mark: "Mark",
  luke: "Luke",
  john: "John",
  acts: "Acts",
  romans: "Rom",
  "1-corinthians": "1Cor",
  "2-corinthians": "2Cor",
  galatians: "Gal",
  ephesians: "Eph",
  philippians: "Phil",
  colossians: "Col",
  "1-thessalonians": "1Thess",
  "2-thessalonians": "2Thess",
  "1-timothy": "1Tim",
  "2-timothy": "2Tim",
  titus: "Titus",
  philemon: "Phlm",
  hebrews: "Heb",
  james: "Jas",
  "1-peter": "1Pet",
  "2-peter": "2Pet",
  "1-john": "1John",
  "2-john": "2John",
  "3-john": "3John",
  jude: "Jude",
  revelation: "Rev",
};

/** App seed metadata per book slug */
export const BOOK_META = {
  genesis: { testament: "OT", name: "Genesis", order_index: 1, chapter_count: 50 },
  exodus: { testament: "OT", name: "Exodus", order_index: 2, chapter_count: 40 },
  leviticus: { testament: "OT", name: "Leviticus", order_index: 3, chapter_count: 27 },
  numbers: { testament: "OT", name: "Numbers", order_index: 4, chapter_count: 36 },
  deuteronomy: { testament: "OT", name: "Deuteronomy", order_index: 5, chapter_count: 34 },
  joshua: { testament: "OT", name: "Joshua", order_index: 6, chapter_count: 24 },
  judges: { testament: "OT", name: "Judges", order_index: 7, chapter_count: 21 },
  ruth: { testament: "OT", name: "Ruth", order_index: 8, chapter_count: 4 },
  "1-samuel": { testament: "OT", name: "1 Samuel", order_index: 9, chapter_count: 31 },
  "2-samuel": { testament: "OT", name: "2 Samuel", order_index: 10, chapter_count: 24 },
  "1-kings": { testament: "OT", name: "1 Kings", order_index: 11, chapter_count: 22 },
  "2-kings": { testament: "OT", name: "2 Kings", order_index: 12, chapter_count: 25 },
  "1-chronicles": { testament: "OT", name: "1 Chronicles", order_index: 13, chapter_count: 29 },
  "2-chronicles": { testament: "OT", name: "2 Chronicles", order_index: 14, chapter_count: 36 },
  ezra: { testament: "OT", name: "Ezra", order_index: 15, chapter_count: 10 },
  nehemiah: { testament: "OT", name: "Nehemiah", order_index: 16, chapter_count: 13 },
  esther: { testament: "OT", name: "Esther", order_index: 17, chapter_count: 10 },
  job: { testament: "OT", name: "Job", order_index: 18, chapter_count: 42 },
  psalms: { testament: "OT", name: "Psalms", order_index: 19, chapter_count: 150 },
  proverbs: { testament: "OT", name: "Proverbs", order_index: 20, chapter_count: 31 },
  ecclesiastes: { testament: "OT", name: "Ecclesiastes", order_index: 21, chapter_count: 12 },
  "song-of-solomon": { testament: "OT", name: "Song of Solomon", order_index: 22, chapter_count: 8 },
  isaiah: { testament: "OT", name: "Isaiah", order_index: 23, chapter_count: 66 },
  jeremiah: { testament: "OT", name: "Jeremiah", order_index: 24, chapter_count: 52 },
  lamentations: { testament: "OT", name: "Lamentations", order_index: 25, chapter_count: 5 },
  ezekiel: { testament: "OT", name: "Ezekiel", order_index: 26, chapter_count: 48 },
  daniel: { testament: "OT", name: "Daniel", order_index: 27, chapter_count: 12 },
  hosea: { testament: "OT", name: "Hosea", order_index: 28, chapter_count: 14 },
  joel: { testament: "OT", name: "Joel", order_index: 29, chapter_count: 3 },
  amos: { testament: "OT", name: "Amos", order_index: 30, chapter_count: 9 },
  obadiah: { testament: "OT", name: "Obadiah", order_index: 31, chapter_count: 1 },
  jonah: { testament: "OT", name: "Jonah", order_index: 32, chapter_count: 4 },
  micah: { testament: "OT", name: "Micah", order_index: 33, chapter_count: 7 },
  nahum: { testament: "OT", name: "Nahum", order_index: 34, chapter_count: 3 },
  habakkuk: { testament: "OT", name: "Habakkuk", order_index: 35, chapter_count: 3 },
  zephaniah: { testament: "OT", name: "Zephaniah", order_index: 36, chapter_count: 3 },
  haggai: { testament: "OT", name: "Haggai", order_index: 37, chapter_count: 2 },
  zechariah: { testament: "OT", name: "Zechariah", order_index: 38, chapter_count: 14 },
  malachi: { testament: "OT", name: "Malachi", order_index: 39, chapter_count: 4 },
  matthew: { testament: "NT", name: "Matthew", order_index: 40, chapter_count: 28 },
  mark: { testament: "NT", name: "Mark", order_index: 41, chapter_count: 16 },
  luke: { testament: "NT", name: "Luke", order_index: 42, chapter_count: 24 },
  john: { testament: "NT", name: "John", order_index: 43, chapter_count: 21 },
  acts: { testament: "NT", name: "Acts", order_index: 44, chapter_count: 28 },
  romans: { testament: "NT", name: "Romans", order_index: 45, chapter_count: 16 },
  "1-corinthians": { testament: "NT", name: "1 Corinthians", order_index: 46, chapter_count: 16 },
  "2-corinthians": { testament: "NT", name: "2 Corinthians", order_index: 47, chapter_count: 13 },
  galatians: { testament: "NT", name: "Galatians", order_index: 48, chapter_count: 6 },
  ephesians: { testament: "NT", name: "Ephesians", order_index: 49, chapter_count: 6 },
  philippians: { testament: "NT", name: "Philippians", order_index: 50, chapter_count: 4 },
  colossians: { testament: "NT", name: "Colossians", order_index: 51, chapter_count: 4 },
  "1-thessalonians": { testament: "NT", name: "1 Thessalonians", order_index: 52, chapter_count: 5 },
  "2-thessalonians": { testament: "NT", name: "2 Thessalonians", order_index: 53, chapter_count: 3 },
  "1-timothy": { testament: "NT", name: "1 Timothy", order_index: 54, chapter_count: 6 },
  "2-timothy": { testament: "NT", name: "2 Timothy", order_index: 55, chapter_count: 4 },
  titus: { testament: "NT", name: "Titus", order_index: 56, chapter_count: 3 },
  philemon: { testament: "NT", name: "Philemon", order_index: 57, chapter_count: 1 },
  hebrews: { testament: "NT", name: "Hebrews", order_index: 58, chapter_count: 13 },
  james: { testament: "NT", name: "James", order_index: 59, chapter_count: 5 },
  "1-peter": { testament: "NT", name: "1 Peter", order_index: 60, chapter_count: 5 },
  "2-peter": { testament: "NT", name: "2 Peter", order_index: 61, chapter_count: 3 },
  "1-john": { testament: "NT", name: "1 John", order_index: 62, chapter_count: 5 },
  "2-john": { testament: "NT", name: "2 John", order_index: 63, chapter_count: 1 },
  "3-john": { testament: "NT", name: "3 John", order_index: 64, chapter_count: 1 },
  jude: { testament: "NT", name: "Jude", order_index: 65, chapter_count: 1 },
  revelation: { testament: "NT", name: "Revelation", order_index: 66, chapter_count: 22 },
};

export function pickMobileSlices(source, slices = MOBILE_SLICES) {
  return slices.map((slice) => {
    const book = source.books.find((entry) => entry.slug === slice.slug);
    if (!book) {
      throw new Error(`Book not found in source: ${slice.slug}`);
    }
    const chapterEntry = book.chapters.find((entry) => entry.number === slice.chapter);
    if (!chapterEntry) {
      throw new Error(`Chapter ${slice.chapter} not found in ${slice.slug}`);
    }
    let selectedVerses = chapterEntry.verses;
    if (slice.verses) {
      const [from, to] = slice.verses;
      selectedVerses = chapterEntry.verses.filter(
        (verse) => verse.number >= from && verse.number <= to
      );
      if (selectedVerses.length === 0) {
        throw new Error(`No verses ${from}-${to} in ${slice.slug} ${slice.chapter}`);
      }
    }
    return {
      testament: book.testament,
      name: book.name,
      slug: book.slug,
      order_index: book.order_index,
      chapter_count: book.chapter_count,
      chapters: [{ number: slice.chapter, verses: selectedVerses }],
    };
  });
}

export function countVerses(seed) {
  return seed.books.reduce(
    (total, book) =>
      total + book.chapters.reduce((sum, chapter) => sum + chapter.verses.length, 0),
    0
  );
}

export function countChapters(seed) {
  return seed.books.reduce((total, book) => total + book.chapters.length, 0);
}
